[package]
name = "embeddedRust"
version = "0.0.1"
authors = ["Fx137 <flufeu@gmail.com>"]
edition = "2018"


[dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
panic-halt = "0.2.0"
stm32f0xx-hal = "0.17.0"